[package]
name = "endless-protos"
version = "1.3.0"
edition = "2021"

[dependencies]
futures-core = { workspace = true }
pbjson = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
serde = { workspace = true }
tonic = { workspace = true }
